
const API='https://gmail.googleapis.com/gmail/v1/users/me';
const READ='https://www.googleapis.com/auth/gmail.readonly';
const SEND='https://www.googleapis.com/auth/gmail.send';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const emailRe=/[A-Za-z0-9.!#$%&'*+\/=?^_{|}~-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g;
const emails=s=>(String(s||'').match(emailRe)||[]).map(x=>x.toLowerCase());
const addr=s=>{const e=emails(s)[0]||'';const n=String(s||'').replace(/<[^>]+>/g,'').replace(e,'').replace(/["']/g,'').trim();return {email:e,name:n||e.split('@')[0]||'不明'}};
const dec=s=>{if(!s)return'';s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const b=Uint8Array.from(atob(s),c=>c.charCodeAt(0));return new TextDecoder().decode(b)};
const enc=s=>{const b=new TextEncoder().encode(s);let x='';for(let i=0;i<b.length;i+=0x8000)x+=String.fromCharCode(...b.slice(i,i+0x8000));return btoa(x).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const hdr=(m,n)=>(m.payload?.headers||[]).find(x=>x.name.toLowerCase()===n.toLowerCase())?.value||'';
const htmlText=h=>{const d=new DOMParser().parseFromString(String(h||''),'text/html');d.querySelectorAll('script,style').forEach(n=>n.remove());return (d.body?.innerText||'').replace(/\n{3,}/g,'\n\n').trim()};
function body(p){if(!p)return'';if(p.mimeType==='text/plain'&&p.body?.data)return dec(p.body.data);for(const x of p.parts||[]){const v=body(x);if(v)return v}if(p.mimeType==='text/html'&&p.body?.data)return htmlText(dec(p.body.data));return''}
function files(p,a=[]){if(p?.filename)a.push({name:p.filename,type:p.mimeType||'',size:p.body?.size||0});for(const x of p?.parts||[])files(x,a);return a}
let token='', expires=0, self='', msgs=[], active='', query='', filter='all', tab='talks', replyId='', timer;
let settings={clientId:localStorage.getItem('mt-client')||'',days:Number(localStorage.getItem('mt-days')||30),max:Number(localStorage.getItem('mt-max')||80)};
let drafts=JSON.parse(localStorage.getItem('mt-drafts')||'{}');
const app=$('.app'), list=$('#talkList'), main=$('#mainPane'), status=$('#statusText'), toast=$('#toast');
function say(t){clearTimeout(timer);toast.textContent=t;toast.classList.add('show');timer=setTimeout(()=>toast.classList.remove('show'),3000)}
function gis(){if(!window.google?.accounts?.oauth2){say('Google認証を読み込み中です。少し待ってください。');return false}if(!settings.clientId){showSettings();say('先にOAuth Client IDを登録してください。');return false}return true}
function getToken(scopes){return new Promise((res,rej)=>{if(!gis())return rej(Error('OAuth設定が必要です'));const c=google.accounts.oauth2.initTokenClient({client_id:settings.clientId,scope:scopes,include_granted_scopes:true,callback:r=>{if(r.error)return rej(Error(r.error));token=r.access_token;expires=Date.now()+(Number(r.expires_in||3600)-60)*1000;res()}});c.requestAccessToken({prompt:token?'':'consent'})})}
async function auth(scopes=READ){if(token&&Date.now()<expires)return;await getToken(scopes)}
async function api(path,opt={}){await auth(opt.scope||READ);let r=await fetch(API+path,{method:opt.method||'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:opt.body});if(r.status===401){token='';await auth(opt.scope||READ);return api(path,opt)}if(!r.ok)throw Error('Gmail API '+r.status);return r.status===204?null:r.json()}
function peer(m){const from=addr(hdr(m,'From')),to=emails(hdr(m,'To')),cc=emails(hdr(m,'Cc'));const out=from.email===self;const e=out?(to.find(x=>x!==self)||cc.find(x=>x!==self)||to[0]||''):from.email;let name=out?addr((hdr(m,'To').split(',').find(x=>emails(x).includes(e))||e)).name:from.name;return {email:e,name:name||e,dir:out?'out':'in'}}
function simple(m){const p=peer(m);return {id:m.id,threadId:m.threadId,labels:m.labelIds||[],at:Number(m.internalDate||Date.now()),from:hdr(m,'From'),to:hdr(m,'To'),cc:hdr(m,'Cc'),subject:hdr(m,'Subject')||'（件名なし）',messageId:hdr(m,'Message-ID'),refs:hdr(m,'References'),inReplyTo:hdr(m,'In-Reply-To'),body:body(m.payload)||m.snippet||'',attachments:files(m.payload),peerEmail:p.email,peerName:p.name,dir:p.dir}}
async function sync(){try{status.textContent='同期中…';const prof=await api('/profile');self=prof.emailAddress.toLowerCase();const q='newer_than:'+Math.max(1,settings.days)+'d';const l=await api('/messages?maxResults='+Math.min(100,settings.max)+'&q='+encodeURIComponent(q));const ids=(l.messages||[]).slice(0,settings.max).map(x=>x.id);const out=[];for(let i=0;i<ids.length;i+=10){const batch=ids.slice(i,i+10);const got=await Promise.all(batch.map(id=>api('/messages/'+id+'?format=full')));out.push(...got.map(simple));status.textContent='読み込み中 '+Math.min(i+10,ids.length)+'/'+ids.length}msgs=out.sort((a,b)=>a.at-b.at);status.textContent=self+' · '+msgs.length+'通';render();say('Gmailを読み込みました')}catch(e){status.textContent='接続エラー';say(e.message)}}
function groups(){const m=new Map();for(const x of msgs){if(!x.peerEmail)continue;let g=m.get(x.peerEmail);if(!g)g={email:x.peerEmail,name:x.peerName,items:[]};g.items.push(x);if(x.peerName)g.name=x.peerName;m.set(x.peerEmail,g)}return [...m.values()].map(g=>{g.items.sort((a,b)=>a.at-b.at);g.last=g.items[g.items.length-1];g.unread=g.items.filter(x=>x.dir==='in'&&x.labels.includes('UNREAD')).length;return g}).sort((a,b)=>b.last.at-a.last.at)}
function time(ms){const d=new Date(ms),n=new Date();if(d.toDateString()===n.toDateString())return d.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});return d.toLocaleDateString('ja-JP',{month:'numeric',day:'numeric'})}
function renderList(){const q=query.trim().toLowerCase();const gs=groups().filter(g=>filter!=='unread'||g.unread).filter(g=>!q||[g.name,g.email,...g.items.flatMap(x=>[x.subject,x.body])].some(s=>String(s).toLowerCase().includes(q)));list.innerHTML=gs.map(g=>'<button class="row '+(active===g.email?'sel':'')+'" data-open="'+esc(g.email)+'"><span class="avatar">'+esc((g.name||'?').slice(0,1))+'</span><span class="rowmain"><span class="r1"><span class="name">'+esc(g.name)+'</span><span class="time">'+time(g.last.at)+'</span></span><span class="subject">'+esc(g.last.subject)+'</span><span class="r1"><span class="preview">'+esc((g.last.body||'').replace(/\s+/g,' ').slice(0,80))+'</span>'+(g.unread?'<span class="badge">'+g.unread+'</span>':'')+'</span></span></button>').join('')||'<div class="empty"><p>該当するトークはありません。</p></div>'}
function renderFilters(){const box=$('#filters');box.innerHTML='<button class="chip '+(filter==='all'?'active':'')+'" data-filter="all">すべて</button><button class="chip '+(filter==='unread'?'active':'')+'" data-filter="unread">未読</button>'}
function render(){renderFilters();renderList();if(tab==='settings')showSettings();else if(active)showChat(active);else if(tab==='talks')showEmpty()}
function showEmpty(){tab='talks';main.innerHTML='<section class="empty"><h2>Gmailを、相手ごとの会話に。</h2><p>同じ相手からのメールは、件名が変わっても1つのトークにまとめます。</p><button class="primary" data-sync>Gmailを読み込む</button></section>';app.classList.remove('inmain')}
function showChat(email){active=email;tab='talks';app.classList.add('inmain');const g=groups().find(x=>x.email===email);if(!g)return showEmpty();if(!replyId||!g.items.some(x=>x.id===replyId&&x.dir==='in'))replyId=(g.items.filter(x=>x.dir==='in').at(-1)||{}).id||'';const bubbles=g.items.map(x=>'<div class="wrap '+(x.dir==='out'?'out':'')+'"><div class="bubble"><div class="subj">'+esc(x.subject)+'</div>'+esc(x.body||'').replace(/\n/g,'<br>')+(x.attachments.length?'<div class="subj" style="margin-top:8px">'+x.attachments.map(f=>'📎 '+esc(f.name)).join('<br>')+'</div>':'')+'</div><div class="meta"><span>'+time(x.at)+'</span>'+(x.dir==='in'?'<button class="replypick" data-reply="'+x.id+'">このメールに返信</button>':'')+'</div></div>').join('');const target=g.items.find(x=>x.id===replyId);const d=drafts[replyId]||'';main.innerHTML='<header class="chathead"><button class="back" data-back>‹</button><div class="avatar">'+esc((g.name||'?').slice(0,1))+'</div><div class="title"><strong>'+esc(g.name)+'</strong><small>'+esc(g.email)+'</small></div></header><div class="msgs">'+bubbles+'</div><form class="composer" id="compose"><div class="target">返信先：'+esc(target?.subject||'受信メールを選択')+'</div><div class="compose"><textarea id="replyText" placeholder="返信を入力">'+esc(d)+'</textarea><button class="send" type="submit">➤</button></div></form>';const ta=$('#replyText');ta?.addEventListener('input',()=>{if(replyId){drafts[replyId]=ta.value;localStorage.setItem('mt-drafts',JSON.stringify(drafts))}});$('#compose')?.addEventListener('submit',sendReply);setTimeout(()=>{const s=$('.msgs');if(s)s.scrollTop=s.scrollHeight},0)}
async function sendReply(e){e.preventDefault();const g=groups().find(x=>x.email===active),t=g?.items.find(x=>x.id===replyId);const text=$('#replyText').value.trim();if(!g||!t||!text)return say('返信先と本文を確認してください。');const subj=/^re:/i.test(t.subject)?t.subject:'Re: '+t.subject;const refs=[t.refs,t.messageId].filter(Boolean).join(' ');const mime=['To: '+g.email,'Subject: '+subj,'In-Reply-To: '+t.messageId,'References: '+refs,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','',text].join('\r\n');if(!confirm('宛先: '+g.email+'\n件名: '+subj+'\n\nこの内容をGmailから送信しますか？'))return;try{await getToken(READ+' '+SEND);await api('/messages/send',{method:'POST',scope:READ+' '+SEND,body:JSON.stringify({raw:enc(mime),threadId:t.threadId})});delete drafts[replyId];localStorage.setItem('mt-drafts',JSON.stringify(drafts));say('送信しました');await sync()}catch(e2){say('送信できません: '+e2.message)}}
function showSettings(){tab='settings';active='';app.classList.add('inmain');$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab==='settings'));main.innerHTML='<div class="page"><h2>設定</h2><p class="page-desc">Google Cloudで作成したOAuth Client IDを登録して、Gmailを接続します。</p><section class="card"><h3>Gmail接続</h3><div class="field"><label>OAuth Client ID</label><input id="clientId" value="'+esc(settings.clientId)+'" placeholder="xxxxx.apps.googleusercontent.com"></div><div class="field"><label>読み込む期間</label><select id="days"><option value="7">7日</option><option value="30">30日</option><option value="90">90日</option></select></div><div class="field"><label>最大メール数</label><select id="max"><option>50</option><option>80</option><option>100</option></select></div><div class="actions"><button class="primary" data-save>保存</button><button class="secondary" data-sync>Gmailを接続・読み込む</button></div></section><section class="card"><h3>接続チェック</h3><div class="'+(location.protocol==='https:'?'ok':'notice')+'">'+(location.protocol==='https:'?'HTTPSで開いています。':'HTTPSで公開してから使ってください。')+'</div><p>この公開テスト版は、Gmailの読み取りと返信送信だけを使います。削除・アーカイブ・既読変更はしません。</p></section></div>';$('#days').value=String(settings.days);$('#max').value=String(settings.max)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open){active=b.dataset.open;replyId='';showChat(active);renderList()}if(b.dataset.filter){filter=b.dataset.filter;render()}if(b.dataset.reply){replyId=b.dataset.reply;showChat(active)}if(b.dataset.back){active='';app.classList.remove('inmain');renderList()}if(b.dataset.tab==='talks'){tab='talks';active='';app.classList.remove('inmain');render()}if(b.dataset.tab==='settings')showSettings();if(b.dataset.sync!==undefined)sync();if(b.dataset.save!==undefined){settings.clientId=$('#clientId').value.trim();settings.days=Number($('#days').value);settings.max=Number($('#max').value);localStorage.setItem('mt-client',settings.clientId);localStorage.setItem('mt-days',settings.days);localStorage.setItem('mt-max',settings.max);say('設定を保存しました')}})
$('#searchInput').addEventListener('input',e=>{query=e.target.value;renderList()});$('#clearSearch').addEventListener('click',()=>{$('#searchInput').value='';query='';renderList()});$('#syncBtn').addEventListener('click',sync);
render();
